SET FOREIGN_KEY_CHECKS=0;


TRUNCATE TABLE airman;
TRUNCATE TABLE app_visits;
TRUNCATE TABLE grade;
TRUNCATE TABLE site;
TRUNCATE TABLE squadron;
TRUNCATE TABLE work_center;

    SET FOREIGN_KEY_CHECKS=1;
